name: Auto Merge Release Commits to Develop

on:
  push:
    branches:
      - release/*

jobs: 
  get_current_branch_name:
    name: Get Current Branch Name
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.get_branch_name.outputs.branch_name }}
    steps:
    - id: get_branch_name
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
  merge_to_develop:
    name: Merge to Develop
    runs-on: ubuntu-latest
    needs: get_current_branch_name
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout develop
      - run: git merge ${{ needs.get_current_branch_name.outputs.current_branch }}
      - run: git push
